### ISSUE TITLE
Birthday Federico

### ISSUE THREAD

**Issue by LorenzoPinto04** [Fog226/birthdays#1]
Ragazzi c'è un problema, manca la data del compleanno di Federico Fogolin. Se qualcuno la conosce può aggiungerla?

**Comment by LorenzoPinto04** [comment]
@Fog226 Riesci a lavorarci tu? Grazie

**Comment by Fog226** [comment]
Closed by commit https://github.com/Fog226/birthdays/commit/9941ad281fa2e351add6de7fc8106811de754c8d
